[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200
verbosity = 5
gas_reports = ["*"]
fs_permissions = [{ access = "read", path = "./src" }]
log_level = "trace"
log_output = ["*"]

[profile.default.fuzz]
runs = 1000

[profile.default.invariant]
runs = 1000
depth = 15

[profile.debug]
verbosity = 5
